apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # ACME server URL for production
    server: https://acme-v02.api.letsencrypt.org/directory
    
    # Email for important notifications (certificate expiration, etc.)
    email: your-email@example.com  # CHANGE THIS!
    
    # Secret to store ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    
    # HTTP01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # ACME server URL for staging (testing)
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    
    # Email for important notifications
    email: your-email@example.com  # CHANGE THIS!
    
    # Secret to store ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    
    # HTTP01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
